### ISSUE TITLE
[FEATURE] Add requirements_dev.txt

### ISSUE THREAD

**Issue by Antyos** [camUrban/PteraSoftware#10]
# Problem Statement

Issue #3 saw the removal of development dependencies from the `requirements.txt` file. I agree with this decision, however, I do not agree with limiting their reference to only the README.

## Proposed Solution

Instead, development dependencies should be added to a `requirements_dev.txt` file.

James Murphy from the YouTube channel mCoding did a great video about packages that goes over this very concept (and others). See how he adds the `requirements_dev.txt` here: <https://youtu.be/DhUpxWjOhME?t=515>.

**Comment by camUrban** [comment]
@Antyos Thanks for the suggestion, this seems like a good idea! I'll work on implementing it in the next release.

**Comment by camUrban** [comment]
This was fixed with the latest commit!
