### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Axlian** [camUrban/PteraSoftware#12]
Firstly, I think PteraSoftware is very useful for analyzing flapping wings.But when I ran the "steady_horseshoe_vortex_lattice_method_solver_example", I can not get the same result with yours.  And when I ran "unsteady_ring_vortex_lattice_method_solver_static_example", I got some errors. I do not  change your codes. I need your help.

**Comment by camUrban** [comment]
Hi @Axlian. Thanks for the bug report. I'll check this out as soon as I get the chance. What version of the software are you using?

**Comment by Axlian** [comment]
I try the develop and the master.

**Comment by camUrban** [comment]
Hi @Axlian. Did you just email me saying that the issue was resolved? If so, I'll close this issue. If not, I'll keep it open and work on this some more!

**Comment by Axlian** [comment]
Please keep it open and help me to solve the problem.

**Comment by camUrban** [comment]
I'm going to close this issue as I haven't been able to reproduce the bug. Please try again after downloading the latest version of the software. Please open a new bug report that follows the template if the bug still exists. That should help me in figuring out what exactly is going wrong.
