### ISSUE TITLE
Create Package Installer

### ISSUE THREAD

**Issue by Zach10a** [camUrban/PteraSoftware#19]
# Creation of a Package Installer

Users with no familiarity of Python or IDE's will be unable to use this software. A fully packaged installer created at this stage will save hassle down the line.

## Proposed Solution

Use of PyInstaller and Inno Setup to create package installer.

**Comment by camUrban** [comment]
Hmm, interesting idea! I haven't used package installers before, so I have some questions. First, would this be simpler than installing Ptera Software with PyPI? Right now, I think you can get the latest version of the package and all the dependencies by using the command `pip install pterasoftware`.

**Comment by Zach10a** [comment]
Hi Cam,

This would be a single installer file, complete with a GUI, that would enable even the most computer-illiterate of users to install and use the package. It would also enable the software to be downloaded from the "Latest Release" section of the Pterasoftware front page.

**Comment by Zach10a** [comment]
Now connected to #6 via #18

**Comment by camUrban** [comment]
Closing this issue as it is it will be fixed in the latest major version release.
