### ISSUE TITLE
Setup Video

### ISSUE THREAD

**Issue by camUrban** [camUrban/PteraSoftware#5]
We should create a setup tutorial video and link to it in the documentation. This should be geared toward a user who doesn't have Python, an IDE, or Ptera Software installed on their computer yet.

**Comment by legitishan** [comment]
Hey, I can help out with this :)

**Comment by camUrban** [comment]
@legitishan Let me know if you need any advice on this!

**Comment by rahulrhdev** [comment]
Hey Team, is this issue still open?

**Comment by user-536667** [comment]
> We should create a setup tutorial video and link to it in the documentation. This should be geared toward a user who doesn't have Python, an IDE, or Ptera Software installed on their computer yet.

Hey camUrban, I was wondering if the video is out yet? I am having a really hard time making heads and tails of it since I have zero experience with python. Anything would work, even a low resolution cam video would suffice. Thank you.

**Comment by camUrban** [comment]
@rahulrhdev Yes, the issue is still open! Feel free to help out with it if you've successfully installed the package.

**Comment by camUrban** [comment]
@user-536667 Hello! Unfortunately, I haven't had any time to work on the video. However, I am on break for the next few weeks, so I'll try to get to it soon. If you're having specific issues, feel free to open a new issue listing what you've tried and what isn't working. Don't be afraid to ask for help; I was also new to Python not too long ago! :smile:

**Comment by camUrban** [comment]
Hey all! I finally got around to making [the setup video](https://www.youtube.com/watch?v=oX8u2ZflJM4) and uploading it to YouTube. @user-536667 I hope this helps you out!

**Comment by user-536667** [comment]
@camUrban Thank you for the video cam, I will look into it and post my queries here if I get stuck somewhere.
